line-length = 100
unsafe-fixes = true
preview = true

[lint]
select = [
    "ARG",
    "B",
    "C4",
    "DTZ",
    "E",
    "F",
    "FAST",
    "FIX001",
    "FLY",
    "FURB",
    "G",
    "I",
    "LOG",
    "NPY",
    "PD",
    "PERF",
    "PGH",
    "PIE",
    "PL",
    "PT",
    "PTH",
    "PYI",
    "Q",
    "RET",
    "RUF",
    "SIM",
    "SLF",
    "SLOT",
    "T10",
    "T20",
    "TCH",
    "TRY",
    "UP",
    "W",
]
ignore = [
    "PLR",  # we do want most Pylint (PL) lints, but many of the refactoring (PLR) ones are really bad
    "PT012",  # can make tests needlessly complicated
    "TRY003",  # none of the linters business what we put in our exceptions
    "RUF029",  # sometimes pointless async functions are mandated by frameworks
    "FAST002",  # conflicts with how dependency_injector works
    "TCH001",  # causes too many issues with Pydantic and the like
    "TCH002",  # as above
    "TCH003",  # as above
]